# Site settings
course_name: Computer Vision
course_description: " This course provides an introduction to computer vision, including fundamentals of image
formation, camera imaging geometry, feature detection and matching, stereo, motion
estimation and tracking, image classification, scene understanding, and deep learning with
neural networks."
course_semester: "Fall 2024"

baseurl: "/csc606" # the subpath of your site, e.g. /blog/
url: "https://alnemari-m.github.io/" # the base hostname & protocol for your site

schoolname: "University of Tabuk"
schoolurl: "https://www.ut.edu.sa"
twitter_username: username 

address: |
    School of Computer Science and Information Technology
    University of Tabuk
    Saudi Arabia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
